Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
   config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      sudo apt-get install -y apache2
    SHELL
  end